### ISSUE TITLE
Barra de navegación del usuario logueado

### ISSUE THREAD

**Issue by amg98** [Proyecto-FIS/frontend#51]
Estaría sabroso si le pusierais al navbar un botón que abra un menú como [este](https://material-ui.com/es/components/drawers/) cuando el usuario esté logueado y muestre las opciones que tienen que ver con su perfil. De momento hay 2 disponibles:

- Redireccionar a /billingprofiles para que pueda editar los destinos de entrega
- Redireccionar a /purchase-history para que pueda ver su historial de compras

La URL /purchase-history me falta hacerle los test para terminarla, aún no está en producción. /billingprofiles sí está.

**Comment by amg98** [comment]
Es solo una idea, podéis hacerlo de otra manera si queréis.

**Comment by 1nt0** [comment]
Sin problemas, iba a hacerlo igualmente cuando tuviera todas las rutas, pero lo puedo ir adelantando.
